GYM/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.dashboard import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('members/', include('apps.members.urls')),
    path('admin/', admin.site.urls),
    path('', views.user_login, name='login'),
    path('dashboard', views.dashboard, name="dashboard"),
    path('logout', views.user_logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('member-registration/', views.add_new_member, name='add_new_member'),
    path('member-list/', views.member_list, name='member_list'),
    path('member/<int:member_id>/', views.member_profile, name='member_profile'),
    path('member/<int:member_id>/edit/', views.edit_member, name='edit_member'),
    path('member/<int:member_id>/delete/', views.delete_member, name='delete_member'),

]

apps/members/models.py
from django.db import models

class Member(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    mobile_number = models.CharField(max_length=15)
    email = models.EmailField(unique=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    area = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    pincode = models.CharField(max_length=10, null=True, blank=True)
    profession = models.CharField(max_length=100, null=True, blank=True)
    sign = models.ImageField(upload_to='signs/', blank=True, null=True)
    identity_type = models.CharField(max_length=50, null=True, blank=True)
    identity_no = models.CharField(max_length=50, null=True, blank=True)
    identity_document_image = models.ImageField(upload_to='identity_docs/', blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class MedicalHistory(models.Model):
    member = models.ForeignKey(Member, related_name='medical_history', on_delete=models.CASCADE)
    condition = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    since = models.DateField()

    def __str__(self):
        return f'{self.member} - {self.condition}'

class EmergencyContact(models.Model):
    member = models.OneToOneField(Member, related_name='emergency_contact', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=15)
    relation = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.member} - {self.name}'

apps/members/forms.py
from django import forms
from .models import Member, MedicalHistory, EmergencyContact

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'mobile_number': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'profile_picture': forms.FileInput(attrs={'class': 'form-control-file'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'area': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'pincode': forms.TextInput(attrs={'class': 'form-control'}),
            'profession': forms.TextInput(attrs={'class': 'form-control'}),
            'sign': forms.FileInput(attrs={'class': 'form-control-file'}),
            'identity_type': forms.TextInput(attrs={'class': 'form-control'}),
            'identity_no': forms.TextInput(attrs={'class': 'form-control'}),
            'identity_document_image': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

class MedicalHistoryForm(forms.ModelForm):
    class Meta:
        model = MedicalHistory
        fields = ['condition', 'type', 'since']
        widgets = {
            'condition': forms.TextInput(attrs={'class': 'form-control'}),
            'type': forms.TextInput(attrs={'class': 'form-control'}),
            'since': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

class EmergencyContactForm(forms.ModelForm):
    class Meta:
        model = EmergencyContact
        fields = ['name', 'mobile', 'relation']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'relation': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/members/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MemberForm, MedicalHistoryForm, EmergencyContactForm
from .models import Member, MedicalHistory, EmergencyContact
from django.forms import modelformset_factory

def add_new_member(request):
    MedicalHistoryFormSet = modelformset_factory(MedicalHistory, form=MedicalHistoryForm, extra=1)
    if request.method == 'POST':
        member_form = MemberForm(request.POST, request.FILES)
        medical_formset = MedicalHistoryFormSet(request.POST, prefix='medical')
        emergency_form = EmergencyContactForm(request.POST, prefix='emergency')
        if member_form.is_valid() and medical_formset.is_valid() and emergency_form.is_valid():
            member = member_form.save()
            for form in medical_formset:
                if form.cleaned_data:
                    medical_history = form.save(commit=False)
                    medical_history.member = member
                    medical_history.save()
            emergency_contact = emergency_form.save(commit=False)
            emergency_contact.member = member
            emergency_contact.save()
            return redirect('member_list')
    else:
        member_form = MemberForm()
        medical_formset = MedicalHistoryFormSet(queryset=MedicalHistory.objects.none(), prefix='medical')
        emergency_form = EmergencyContactForm(prefix='emergency')
    return render(request, 'members/add_new_member.html', {
        'form': member_form,
        'medical_formset': medical_formset,
        'emergency_form': emergency_form
    })

def member_profile(request, member_id):
    member = Member.objects.get(id=member_id)
    return render(request, 'members/member_profile.html', {'member': member})



def edit_member(request, member_id):
    member = Member.objects.get(id=member_id)
    if request.method == 'POST':
        form = MemberForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            return redirect('member_list')
    else:
        form = MemberForm(instance=member)
    return render(request, 'members/edit_member.html', {'form': form})

from django.core.paginator import Paginator


from django.db.models import Q

def member_list(request):
    member_list = Member.objects.all()
    query = request.GET.get('q')
    if query:
        member_list = member_list.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(email__icontains=query) |
            Q(mobile_number__icontains=query)
        ).distinct()

    paginator = Paginator(member_list, 10)  # Show 10 members per page.

    page_number = request.GET.get('page')
    members = paginator.get_page(page_number)
    return render(request, 'members/member_list.html', {'members': members})

def delete_member(request, member_id):
    member = get_object_or_404(Member, id=member_id)
    member.delete()
    return redirect('member_list')

templates/members/add_new_member.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Add New Member</h4>
                <form method="post" enctype="multipart/form-data" class="form-sample">
                    {% csrf_token %}
                    <p class="card-description"> Personal info </p>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">First Name</label>
                                <div class="col-sm-9">
                                    {{ form.first_name }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Last Name</label>
                                <div class="col-sm-9">
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Gender</label>
                                <div class="col-sm-9">
                                    {{ form.gender }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Date of Birth</label>
                                <div class="col-sm-9">
                                    {{ form.date_of_birth }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Age</label>
                                <div class="col-sm-9">
                                    {{ form.age }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Profession</label>
                                <div class="col-sm-9">
                                    {{ form.profession }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="card-description"> Contact details </p>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Mobile Number</label>
                                <div class="col-sm-9">
                                    {{ form.mobile_number }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Email</label>
                                <div class="col-sm-9">
                                    {{ form.email }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Address</label>
                                <div class="col-sm-9">
                                    {{ form.address }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Area</label>
                                <div class="col-sm-9">
                                    {{ form.area }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">City</label>
                                <div class="col-sm-9">
                                    {{ form.city }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">State</label>
                                <div class="col-sm-9">
                                    {{ form.state }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Pincode</label>
                                <div class="col-sm-9">
                                    {{ form.pincode }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="card-description"> Documents </p>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Profile Picture</label>
                                <div class="col-sm-9">
                                    {{ form.profile_picture }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Signature</label>
                                <div class="col-sm-9">
                                    {{ form.sign }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Identity Type</label>
                                <div class="col-sm-9">
                                    {{ form.identity_type }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Identity Number</label>
                                <div class="col-sm-9">
                                    {{ form.identity_no }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Identity Document</label>
                                <div class="col-sm-9">
                                    {{ form.identity_document_image }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="card-description"> Medical History </p>
                    {{ medical_formset.management_form }}
                    {% for form in medical_formset %}
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Condition</label>
                                {{ form.condition }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Type</label>
                                {{ form.type }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Since</label>
                                {{ form.since }}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <p class="card-description"> Emergency Contact </p>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Name</label>
                                {{ emergency_form.name }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Mobile</label>
                                {{ emergency_form.mobile }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Relation</label>
                                {{ emergency_form.relation }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2"> Submit </button>
                    <button class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/members/edit_member.html
{% extends 'base.html' %}

{% block content %}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Edit Member</h4>
            <p class="card-description"> Basic form elements </p>
            <form method="post" enctype="multipart/form-data" class="forms-sample">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_first_name">First Name</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="id_email">Email address</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="id_mobile_number">Mobile Number</label>
                    {{ form.mobile_number }}
                </div>
                <div class="form-group">
                    <label for="id_age">Age</label>
                    {{ form.age }}
                </div>
                <div class="form-group">
                    <label for="id_gender">Gender</label>
                    {{ form.gender }}
                </div>
                <div class="form-group">
                    <label for="id_date_of_birth">Date of Birth</label>
                    {{ form.date_of_birth }}
                </div>
                <div class="form-group">
                    <label for="id_address">Address</label>
                    {{ form.address }}
                </div>
                <div class="form-group">
                    <label for="id_area">Area</label>
                    {{ form.area }}
                </div>
                <div class="form-group">
                    <label for="id_city">City</label>
                    {{ form.city }}
                </div>
                <div class="form-group">
                    <label for="id_state">State</label>
                    {{ form.state }}
                </div>
                <div class="form-group">
                    <label for="id_pincode">Pincode</label>
                    {{ form.pincode }}
                </div>
                <div class="form-group">
                    <label for="id_profession">Profession</label>
                    {{ form.profession }}
                </div>
                <div class="form-group">
                    <label>Profile Picture</label>
                    {{ form.profile_picture }}
                </div>
                <div class="form-group">
                    <label>Signature</label>
                    {{ form.sign }}
                </div>
                <div class="form-group">
                    <label for="id_identity_type">Identity Type</label>
                    {{ form.identity_type }}
                </div>
                <div class="form-group">
                    <label for="id_identity_no">Identity Number</label>
                    {{ form.identity_no }}
                </div>
                <div class="form-group">
                    <label>Identity Document</label>
                    {{ form.identity_document_image }}
                </div>
                <button type="submit" class="btn btn-primary mr-2"> Submit </button>
                <button class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/members/member_list.html
{% extends 'base.html' %}

{% block content %}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Member List</h4>
            <div class="d-flex justify-content-between">
                <form method="get" action="{% url 'member_list' %}" class="form-inline">
                    <input type="text" name="q" placeholder="Search members" value="{{ request.GET.q }}" class="form-control mb-2 mr-sm-2">
                    <button type="submit" class="btn btn-primary mb-2">Search</button>
                </form>
                <a href="{% url 'add_new_member' %}" class="btn btn-success mb-2">Add New Member</a>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th> User </th>
                            <th> First name </th>
                            <th> Email </th>
                            <th> Mobile </th>
                            <th> Actions </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for member in members %}
                        <tr>
                            <td class="py-1">
                                {% if member.profile_picture %}
                                <img src="{{ member.profile_picture.url }}" alt="image" />
                                {% endif %}
                            </td>
                            <td><a href="{% url 'member_profile' member.id %}">{{ member.first_name }} {{ member.last_name }}</a></td>
                            <td>{{ member.email }}</td>
                            <td>{{ member.mobile_number }}</td>
                            <td>
                                <a href="{% url 'edit_member' member.id %}" class="btn btn-primary">Edit</a>
                                <a href="{% url 'delete_member' member.id %}" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="pagination">
                <span class="step-links">
                    {% if members.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ members.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ members.number }} of {{ members.paginator.num_pages }}.
                    </span>

                    {% if members.has_next %}
                        <a href="?page={{ members.next_page_number }}">next</a>
                        <a href="?page={{ members.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/members/member_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{ member.first_name }} {{ member.last_name }}</h4>
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Email:</strong> {{ member.email }}</p>
                    <p><strong>Mobile:</strong> {{ member.mobile_number }}</p>
                    <p><strong>Age:</strong> {{ member.age }}</p>
                    <p><strong>Gender:</strong> {{ member.gender }}</p>
                    <p><strong>Date of Birth:</strong> {{ member.date_of_birth }}</p>
                    <p><strong>Address:</strong> {{ member.address }}</p>
                    <p><strong>Area:</strong> {{ member.area }}</p>
                    <p><strong>State:</strong> {{ member.state }}</p>
                    <p><strong>City:</strong> {{ member.city }}</p>
                    <p><strong>Pincode:</strong> {{ member.pincode }}</p>
                    <p><strong>Profession:</strong> {{ member.profession }}</p>
                </div>
                <div class="col-md-6">
                    {% if member.profile_picture %}
                        <img src="{{ member.profile_picture.url }}" alt="Profile Picture" class="img-fluid">
                    {% endif %}
                    {% if member.sign %}
                        <img src="{{ member.sign.url }}" alt="Signature" class="img-fluid">
                    {% endif %}
                    {% if member.identity_document_image %}
                        <img src="{{ member.identity_document_image.url }}" alt="Identity Document" class="img-fluid">
                    {% endif %}
                </div>
            </div>

            <h3>Medical History</h3>
            <ul>
            {% for history in member.medical_history.all %}
                <li>{{ history.condition }} ({{ history.type }}) - Since: {{ history.since }}</li>
            {% endfor %}
            </ul>

            <h3>Emergency Contact</h3>
            <p><strong>Name:</strong> {{ member.emergency_contact.name }}</p>
            <p><strong>Mobile:</strong> {{ member.emergency_contact.mobile }}</p>
            <p><strong>Relation:</strong> {{ member.emergency_contact.relation }}</p>

            <a href="{% url 'edit_member' member.id %}" class="btn btn-primary">Edit</a>
            <a href="{% url 'member_list' %}" class="btn btn-secondary">Back to List</a>
        </div>
    </div>
</div>
{% endblock %}